// Copyright 2026 Golf Cart Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <golfcart_aruco_localizer/solver.hpp>

#include <gtest/gtest.h>

#include <random>
#include <vector>

namespace golfcart::aruco_localizer
{
namespace
{

constexpr double kMarkerSize = 0.384;

Eigen::Matrix3d testIntrinsics()
{
  Eigen::Matrix3d k = Eigen::Matrix3d::Identity();
  k(0, 0) = 900.0;
  k(1, 1) = 900.0;
  k(0, 2) = 960.0;
  k(1, 2) = 640.0;
  return k;
}

/// Camera looking along base +x, optical convention (z forward, x right, y down).
Eigen::Isometry3d forwardCamera()
{
  Eigen::Isometry3d t = Eigen::Isometry3d::Identity();
  t.linear() = (Eigen::AngleAxisd(-M_PI_2, Eigen::Vector3d::UnitZ()) *
                Eigen::AngleAxisd(-M_PI_2, Eigen::Vector3d::UnitX()))
                 .toRotationMatrix();
  t.translation() = Eigen::Vector3d{0.0, 0.0, 0.6};
  return t;
}

/// Build an observation of a board placed so it lands at `cam_to_tag` for the
/// given vehicle pose. Pixels are generated by projecting the true corners, so
/// with no noise the solver's residual at the true pose is exactly zero.
BoardObservation makeBoard(
  std::uint32_t id, const Eigen::Isometry3d & map_to_base,
  const Eigen::Isometry3d & cam_to_tag, double corner_noise_px = 0.0,
  std::mt19937 * rng = nullptr)
{
  BoardObservation b;
  b.id = id;
  b.camera = "front";
  b.base_to_cam = forwardCamera();
  b.k = testIntrinsics();
  b.marker_size = kMarkerSize;
  b.position_stddev = 0.02;
  b.map_to_tag = map_to_base * b.base_to_cam * cam_to_tag;

  std::normal_distribution<double> noise(0.0, corner_noise_px);
  const auto local = tagLocalCorners(kMarkerSize);
  for (std::size_t c = 0; c < kNumCorners; ++c) {
    const Eigen::Vector3d x = cam_to_tag * local[c];
    Eigen::Vector2d uv{
      b.k(0, 0) * x.x() / x.z() + b.k(0, 2),
      b.k(1, 1) * x.y() / x.z() + b.k(1, 2)};
    if (rng != nullptr && corner_noise_px > 0.0) {
      uv.x() += noise(*rng);
      uv.y() += noise(*rng);
    }
    b.pixels[c] = uv;
  }

  // The true solution, plus a plausible flipped alternate.
  b.cam_to_tag_1 = cam_to_tag;
  b.error_1 = 0.01;
  Eigen::Isometry3d flipped = cam_to_tag;
  flipped.linear() = cam_to_tag.linear() *
    Eigen::AngleAxisd(0.6, Eigen::Vector3d::UnitX()).toRotationMatrix();
  b.cam_to_tag_2 = flipped;
  b.error_2 = 1.0;
  return b;
}

/// A board in front of the camera, tilted so the view is oblique.
Eigen::Isometry3d viewAt(double x, double y, double z, double tilt)
{
  Eigen::Isometry3d t = Eigen::Isometry3d::Identity();
  t.linear() = (Eigen::AngleAxisd(M_PI, Eigen::Vector3d::UnitY()) *
                Eigen::AngleAxisd(tilt, Eigen::Vector3d::UnitX()))
                 .toRotationMatrix();
  t.translation() = Eigen::Vector3d{x, y, z};
  return t;
}

Eigen::Isometry3d vehicleAt(double x, double y, double yaw)
{
  Eigen::Isometry3d t = Eigen::Isometry3d::Identity();
  t.linear() = Eigen::AngleAxisd(yaw, Eigen::Vector3d::UnitZ()).toRotationMatrix();
  t.translation() = Eigen::Vector3d{x, y, 0.0};
  return t;
}

std::vector<std::pair<std::size_t, int>> allTrue(std::size_t n)
{
  std::vector<std::pair<std::size_t, int>> f;
  for (std::size_t i = 0; i < n; ++i) {
    f.emplace_back(i, 0);
  }
  return f;
}

double angleBetween(const Eigen::Isometry3d & a, const Eigen::Isometry3d & b)
{
  return std::abs(Eigen::AngleAxisd(a.linear().transpose() * b.linear()).angle());
}

}  // namespace

// ── the geometry chain ──────────────────────────────────────────────────────

TEST(Solver, ZeroNoiseRecoversTheTruePose)
{
  const Eigen::Isometry3d truth = vehicleAt(2.0, 1.0, 0.4);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(0.5, -0.2, 4.0, 0.4)),
    makeBoard(2, truth, viewAt(-0.6, 0.1, 5.0, -0.5)),
    makeBoard(3, truth, viewAt(0.1, 0.3, 6.5, 0.7))};

  // Deliberately seed away from truth, so this tests convergence rather than
  // the seed being handed back unchanged.
  Eigen::Isometry3d seed = truth;
  seed.translation() += Eigen::Vector3d{0.3, -0.25, 0.0};
  seed.linear() = (Eigen::AngleAxisd(0.08, Eigen::Vector3d::UnitZ()) * seed.linear());

  const SolveResult r = solvePose(boards, allTrue(boards.size()), seed);

  ASSERT_TRUE(r.ok) << r.reason;
  EXPECT_LT((r.pose.translation() - truth.translation()).norm(), 1e-6)
    << "position off by " << (r.pose.translation() - truth.translation()).norm() << " m";
  EXPECT_LT(angleBetween(r.pose, truth), 1e-6)
    << "orientation off by " << angleBetween(r.pose, truth) * 180.0 / M_PI << " deg";
}

TEST(Solver, NoiseGivesCentimetreScaleError)
{
  std::mt19937 rng(7);
  const Eigen::Isometry3d truth = vehicleAt(2.0, 1.0, 0.4);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(0.5, -0.2, 4.0, 0.4), 0.3, &rng),
    makeBoard(2, truth, viewAt(-0.6, 0.1, 5.0, -0.5), 0.3, &rng),
    makeBoard(3, truth, viewAt(0.1, 0.3, 6.5, 0.7), 0.3, &rng)};

  const SolveResult r = solvePose(boards, allTrue(boards.size()), truth);
  ASSERT_TRUE(r.ok) << r.reason;

  const double error = (r.pose.translation() - truth.translation()).norm();
  EXPECT_GT(error, 1e-9) << "noise had no effect — is it applied?";
  EXPECT_LT(error, 0.15) << "0.3 px of corner noise moved the pose " << error << " m";
}

// ── covariance and degeneracy ───────────────────────────────────────────────

TEST(Solver, CovarianceGrowsWhenTheConstellationCollapses)
{
  const Eigen::Isometry3d truth = vehicleAt(0.0, 0.0, 0.0);

  // Well spread: boards at different bearings, depths and tilts.
  std::vector<BoardObservation> spread{
    makeBoard(1, truth, viewAt(1.2, -0.3, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.2, 0.2, 6.0, -0.6)),
    makeBoard(3, truth, viewAt(0.0, 0.4, 9.0, 0.3))};

  // Clustered: three boards almost on top of each other, same depth. This is
  // the near-null direction of the design — a rotation about the centroid of
  // the correspondences moves each point only in proportion to its offset from
  // that centroid, so a tight cluster barely constrains it.
  std::vector<BoardObservation> clustered{
    makeBoard(1, truth, viewAt(0.00, 0.0, 6.0, 0.4)),
    makeBoard(2, truth, viewAt(0.06, 0.0, 6.0, 0.4)),
    makeBoard(3, truth, viewAt(-0.06, 0.0, 6.0, 0.4))};

  const SolveResult a = solvePose(spread, allTrue(3), truth);
  const SolveResult b = solvePose(clustered, allTrue(3), truth);
  ASSERT_TRUE(a.ok) << a.reason;
  ASSERT_TRUE(b.ok) << b.reason;

  EXPECT_GT(b.covariance.trace(), a.covariance.trace())
    << "a clustered constellation must report more uncertainty than a spread one";
  EXPECT_GT(b.observability.condition_number, a.observability.condition_number)
    << "clustered geometry must be worse conditioned";
  EXPECT_GT(a.observability.normal_spread_deg, b.observability.normal_spread_deg);
}

TEST(Solver, CovarianceIsNeverZeroAndNeverInfinite)
{
  // A singular information matrix is what an unobservable direction looks
  // like. It must saturate, not throw, explode, or come back as zero — a zero
  // variance reads downstream as "exact", and nothing can contradict it.
  const Eigen::Matrix<double, 6, 6> singular = Eigen::Matrix<double, 6, 6>::Zero();
  const auto cov = saturatedCovariance(singular, 1.0, 100.0, 1.0);

  ASSERT_TRUE(cov.allFinite()) << "saturation produced a non-finite covariance";
  for (int i = 0; i < 6; ++i) {
    EXPECT_GT(cov(i, i), 0.0) << "diagonal " << i << " came back zero";
    EXPECT_LE(cov(i, i), 100.0 + 1e-9) << "diagonal " << i << " exceeded the cap";
  }
}

TEST(Solver, CovarianceTracksCornerNoise)
{
  const Eigen::Isometry3d truth = vehicleAt(0.0, 0.0, 0.0);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4)),
    makeBoard(3, truth, viewAt(0.2, 0.3, 7.0, 0.3))};

  SolveOptions tight;
  tight.corner_sigma_px = 0.1;
  SolveOptions loose;
  loose.corner_sigma_px = 1.0;

  const auto a = solvePose(boards, allTrue(3), truth, tight);
  const auto b = solvePose(boards, allTrue(3), truth, loose);
  ASSERT_TRUE(a.ok && b.ok);

  EXPECT_GT(b.covariance.trace(), a.covariance.trace())
    << "raising corner sigma must raise the reported uncertainty";
}

// ── robustness ──────────────────────────────────────────────────────────────

TEST(Solver, OneDisplacedBoardDoesNotDragTheSolution)
{
  const Eigen::Isometry3d truth = vehicleAt(1.0, 0.5, 0.2);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4)),
    makeBoard(3, truth, viewAt(0.2, 0.3, 7.0, 0.3)),
    makeBoard(4, truth, viewAt(-0.4, -0.3, 5.0, 0.2))};

  // Board 4's map entry is wrong by 30 cm: its pixels say one thing, the map
  // says another. All four of its corners are wrong together, which is exactly
  // why the Huber kernel is applied per board rather than per corner.
  boards[3].map_to_tag.translation() += Eigen::Vector3d{0.3, 0.0, 0.0};

  const SolveResult r = solvePose(boards, allTrue(4), truth);
  ASSERT_TRUE(r.ok) << r.reason;

  EXPECT_LT((r.pose.translation() - truth.translation()).norm(), 0.05)
    << "one bad board pulled the solution "
    << (r.pose.translation() - truth.translation()).norm() << " m off";

  // And it must be visible as the offender, so integrity monitoring has
  // something to act on.
  EXPECT_GT(r.board_residual_px.at(4), r.board_residual_px.at(1) * 5.0)
    << "the displaced board should stand out in the per-board residuals";
}

// ── consensus ───────────────────────────────────────────────────────────────

TEST(Consensus, TwoBoardsAgreeWithoutAnyPrior)
{
  const Eigen::Isometry3d truth = vehicleAt(1.0, -0.5, 0.3);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4))};

  const ConsensusResult c = resolveFlips(boards);
  ASSERT_TRUE(c.ok) << c.reason;
  EXPECT_FALSE(c.tie);
  EXPECT_EQ(c.members.size(), 2U);
  for (const auto & [index, solution] : c.members) {
    EXPECT_EQ(solution, 0) << "board " << index << " picked the flipped solution";
  }
  EXPECT_LT((c.seed.translation() - truth.translation()).norm(), 1e-6);
}

TEST(Consensus, LoneAmbiguousBoardIsRejected)
{
  const Eigen::Isometry3d truth = vehicleAt(0.0, 0.0, 0.0);
  std::vector<BoardObservation> boards{makeBoard(1, truth, viewAt(0.5, 0.0, 4.0, 0.4))};

  // Both solutions fit about equally well: the board is telling us it cannot
  // resolve its own orientation.
  boards[0].error_1 = 0.9;
  boards[0].error_2 = 1.0;

  const ConsensusResult c = resolveFlips(boards);
  EXPECT_FALSE(c.ok);
  EXPECT_NE(c.reason.find("ambiguous"), std::string::npos) << c.reason;
}

TEST(Consensus, LoneUnambiguousBoardIsAccepted)
{
  const Eigen::Isometry3d truth = vehicleAt(0.0, 0.0, 0.0);
  std::vector<BoardObservation> boards{makeBoard(1, truth, viewAt(0.5, 0.0, 4.0, 0.4))};
  boards[0].error_1 = 0.01;
  boards[0].error_2 = 1.0;

  const ConsensusResult c = resolveFlips(boards);
  ASSERT_TRUE(c.ok) << c.reason;
  EXPECT_EQ(c.members.size(), 1U);
}

TEST(Consensus, ABoardWhoseMapEntryIsWrongFallsOutOfTheCluster)
{
  const Eigen::Isometry3d truth = vehicleAt(1.0, 0.5, 0.0);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4)),
    makeBoard(3, truth, viewAt(0.2, 0.3, 7.0, 0.3))};

  // Board 3 is somewhere else entirely, so neither of its solutions agrees.
  boards[2].map_to_tag.translation() += Eigen::Vector3d{3.0, 2.0, 0.0};

  const ConsensusResult c = resolveFlips(boards);
  ASSERT_TRUE(c.ok) << c.reason;
  EXPECT_EQ(c.members.size(), 2U);
  ASSERT_EQ(c.outliers.size(), 1U);
  EXPECT_EQ(c.outliers.front(), 3U);
}

// ── the Jacobian ────────────────────────────────────────────────────────────

TEST(Solver, ExpSe3AndSkewAgreeWithTheirDefinitions)
{
  const Eigen::Vector3d a{1.0, 2.0, 3.0};
  const Eigen::Vector3d b{-0.5, 0.25, 2.0};
  EXPECT_TRUE((skew(a) * b).isApprox(a.cross(b), 1e-12));

  Eigen::Matrix<double, 6, 1> xi;
  xi << 0.1, -0.2, 0.3, 0.0, 0.0, 0.0;
  const auto t = expSe3(xi);
  EXPECT_TRUE(t.linear().isApprox(Eigen::Matrix3d::Identity(), 1e-12));
  EXPECT_TRUE(t.translation().isApprox(xi.head<3>(), 1e-12));
}

// The two tests below pin the gap the consensus gate lives in. They exist
// because the gate was nearly widened to chase intermittent "no two boards
// agree" — which would have traded a stalled fix for a confidently wrong one.
// Measured over the admitted view window at 5.5 m under 0.3 px corner noise,
// two boards disagree by 0.27 m / 2.8 deg at the 99th percentile; a flip puts
// them tens of metres apart. The tolerances sit between those, and must stay
// there.
TEST(Consensus, NoiseLevelDisagreementIsStillAgreement)
{
  const Eigen::Isometry3d truth = vehicleAt(1.0, -0.5, 0.3);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4))};

  // Displace one board's implied pose to the measured 99th percentile of
  // ordinary noise. Two good boards must not be split by their own scatter.
  boards[1].map_to_tag.translation() += Eigen::Vector3d{0.2, 0.1, 0.05};  // 0.23 m

  const ConsensusResult c = resolveFlips(boards);
  EXPECT_TRUE(c.ok) << c.reason;
  EXPECT_EQ(c.members.size(), 2U) << "two boards were split by noise-level disagreement";
}

TEST(Consensus, FlipLevelDisagreementIsRejected)
{
  const Eigen::Isometry3d truth = vehicleAt(1.0, -0.5, 0.3);
  std::vector<BoardObservation> boards{
    makeBoard(1, truth, viewAt(1.0, -0.2, 4.0, 0.5)),
    makeBoard(2, truth, viewAt(-1.0, 0.2, 5.5, -0.4))};

  // A flip is not a large noise sample; it is a different answer. Well short of
  // the tens of metres one really produces, and it must already be rejected.
  boards[1].map_to_tag.translation() += Eigen::Vector3d{3.0, 0.0, 0.0};

  const ConsensusResult c = resolveFlips(boards);
  EXPECT_FALSE(c.ok && c.members.size() == 2U)
    << "a flipped board was accepted as corroboration";
}

}  // namespace golfcart::aruco_localizer
